Labs/Components/CartViewComponent.cs
using Labs.Extensions;
using Labs.Models;
using Microsoft.AspNetCore.Mvc;

namespace Labs.Components;

public class CartViewComponent : ViewComponent
{
    private Cart _cart;
    public CartViewComponent(Cart cart)
    {
        _cart = cart;
    }

    public IViewComponentResult Invoke()
    {
        var cart = HttpContext.Session.Get<Cart>("cart");
        return View(cart);
    }
}

Labs/Components/MenuViewComponent.cs
using Labs.Models;
using Microsoft.AspNetCore.Mvc;

namespace Labs.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
            new MenuItem{ Controller="Product", Action="Index", Text="Каталог"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"}
        };

        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller)
                ?? false;
                // Название зоны совпадает?
                var _matchArea = area?.Equals(item.Area) ?? false;
                // Если есть совпадение, то сделать элемент меню активным
                // (применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }

    }
}

Labs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Labs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Labs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-md navbar-light bg-light box-shadow">
            <div class="container">
                <!-- меню сайта -->
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">Labs</a>
                @await Component.InvokeAsync("Menu")
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </div>
        </nav> <!-- Панель навигации - конец -->
    </header><!-- header - конец -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="fixed-bottom">
        <div class="navbar navbar-light navbar-expand-md bg-light box-shadow">
            <div class="container">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>

    </footer>
    <script src="lib/jquery/dist/jquery.js"></script>
    <script src="lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

Labs/Views/Shared/_UserPartial.cshtml
@using Labs.DAL.Entities
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> signInManager

<div class="d-flex">
@if (signInManager.IsSignedIn(User))
{
        @await Component.InvokeAsync("Cart")
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img img-action="GetAvatar"
                         img-controller="Image"
                         width="30" alt="User"
                         class="rounded bg-light" />
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li>
                        <a class="dropdown-item" href="#">
                            <img img-action="GetAvatar"
                                 img-controller="Image"
                                 width="30" alt="User"
                                 class="rounded bg-light" />
                            @User.Identity?.Name
                        </a>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-controller="Cart" asp-action="Index">Мои товары</a></li>
                    <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">Log off</a></li>
                </ul>
            </li>
        </ul>
}
else
{
    <nav class="navbar-nav me-auto mb-2 mb-lg-0">
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link"
                   asp-area="Identity"
                   asp-page="/Account/Login">
                    Войти
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link"
                   asp-area="Identity"
                   asp-page="/Account/Register">
                    Зарегистрироваться
                </a>
            </li>
        </ul>
    </nav>
}
</div>